// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_JuD8fHElyFn4M8nW4ddhLaP6XA--BQ',
    appId: '1:171204720354:web:47c34d8b2e4d5f89c410bb',
    messagingSenderId: '171204720354',
    projectId: 'mynotes-0129',
    authDomain: 'mynotes-0129.firebaseapp.com',
    storageBucket: 'mynotes-0129.appspot.com',
    measurementId: 'G-YCNDNSP9C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVn-DJZEUVGH6w5UQANbv6Bi-Nq0lZZQU',
    appId: '1:171204720354:android:693ac1b51f1a29f8c410bb',
    messagingSenderId: '171204720354',
    projectId: 'mynotes-0129',
    storageBucket: 'mynotes-0129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAigRgEPRyjt0tWlGz-U59swXXB4xthaok',
    appId: '1:171204720354:ios:27f98314c83c51d1c410bb',
    messagingSenderId: '171204720354',
    projectId: 'mynotes-0129',
    storageBucket: 'mynotes-0129.appspot.com',
    iosClientId: '171204720354-tahhgm0rg09r3k2e3dc2btbeo8ln286l.apps.googleusercontent.com',
    iosBundleId: 'hp.dream.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAigRgEPRyjt0tWlGz-U59swXXB4xthaok',
    appId: '1:171204720354:ios:64f3f745794c87cbc410bb',
    messagingSenderId: '171204720354',
    projectId: 'mynotes-0129',
    storageBucket: 'mynotes-0129.appspot.com',
    iosClientId: '171204720354-i5cgl13m863sl7mq8ro7i10p229dvl58.apps.googleusercontent.com',
    iosBundleId: 'hp.dream.mynotes.RunnerTests',
  );
}
